### PR TITLE
ref(symcache): Read old/new SymCache and write new SymCache format (NATIVE-375)

### LINKED ISSUE #178: symcache line definition is capping to 65k
I'm having issues symbolicating files with more than 65k lines like [sqlite3.c](https://raw.githubusercontent.com/qt/qtbase/dev/src/3rdparty/sqlite/sqlite3.c). Everything points to `LineRecord` definition (https://github.com/getsentry/symbolic/blob/master/symcache/src/format.rs#L242) and writer logic (`line: std::cmp::min(line.line, std::u16::MAX.into()) as u16`)  where `u16` should be `u32` instead (https://github.com/getsentry/symbolic/blob/master/symcache/src/writer.rs#L446)

e.g.:

The following symbolicated frame should have line `115772` but it's clipped to `65535`

```json
{
        "abs_path": "../../../../../../../third-party/sqlite3/src/sqlite3.c",
        "base_dir": "../../../../../../../third-party/sqlite3/src",
        "comp_dir": ".",
        "filename": "sqlite3.c",
        "function_name": "sqlite3_exec",
        "instr_addr": 6815687,
        "lang": "c",
        "line": 65535,
        "line_addr": 6815614,
        "rel_path": "../../../../../../../third-party/sqlite3/src/sqlite3.c",
        "sym_addr": 6815388,
        "symbol": "sqlite3_exec"
}
```

### LINKED ISSUE #330: symcache FuncRecord parent offset is capping to 65k
I'm having issues extracting symcache from pdb which in`parent_offset` larger than `u16`. It points to FuncRecord definition https://github.com/getsentry/symbolic/blob/461173aa47f7b21454158b427c9b80410738aac5/symbolic-symcache/src/format.rs#L207 and write logic https://github.com/getsentry/symbolic/blob/461173aa47f7b21454158b427c9b80410738aac5/symbolic-symcache/src/writer.rs#L660-L662

We expect to support 32 / 64 platform only, so it would be ok to use a u32 parent_offset instead. But it's hard to make a backwards compatible modification since we already have many symcache files extracted in u16 size.

### LINKED ISSUE #405: Splitting of >65k functions in symcache format creates incorrect symbol addresses
### Environment

We use the symbolic Python API to look up addresses in a symcache, here: https://github.com/mozilla-services/tecken/blob/b0ab02f87626531dae3123bb71652b0cf0779ef5/eliot-service/eliot/symbolicate_resource.py#L409-L428

### Steps to Reproduce

```
% cd symbolic
% wget -o XUL.sym.gz https://symbols.mozilla.org/XUL/395F7EC110E43068A7EE11BEA458C5210/XUL.sym
% gzip -d XUL.sym.gz
% cargo run --release -p symcache_debug -- -d XUL.sym -w -c long-drawquad-xul.symcache
% cargo run --release -p symcache_debug -- -c long-drawquad-xul.symcache --symbols | grep draw_quad_spans
```

### Expected Result

There should only be one symbol for the function `void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)`, at address 0x39bce0.
Or at least, looking up an address anywhere inside the function should return a result with symbol address 0x39bce0.

### Actual Result

There are three symbols for this function:

```
          39bce0 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
          3abdc3 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
          3bbe06 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
```

Looking up address 0x3b7b74 returns a result with symbol address 0x3abdc3. But in reality there is no symbol at 0x3abdc3 - the function starts at 0x39bce0.

### Debugging

`draw_quad_spans` is a very long function. It goes from 0x39bce0 to 0x3ca0cc, that's 189 420 bytes.
The symcache writer splits up functions whose length does not fit into a u16, here:

https://github.com/getsentry/symbolic/blob/49bd892c2efbfcf502d20164dac942101ddb43cb/symbolic-symcache/src/writer.rs#L484-L491

It would be great if this could be done in a way that doesn't invent new symbol addresses.

### Why is this important

In the Mozilla symbolication API we calculate a "function offset" for each address that gets looked up: this is the offset between the function start and the address.
In the Firefox profiler we group functions that start at the same address into the same call node.

In the future, we want to show an assembly view in the Firefox profiler. This assembly view should show the assembly code of the entire function. It also needs to start at a valid instruction address.
If the function is split, this means that the assembly view would not be able to show the entire function; it would only show an arbitrary 65k excerpt of it. And it might even have trouble disassembling the machine code because the synthetic symbol address might not fall on an instruction boundary.

### PR DESCRIPTION
**Pull request by loewenheim**
This adds compatibility types/functions that generalize over the old and new symcache formats while keeping the API the same.

The `Preamble` struct from the old symcache is extracted into a new module to aid in deciding which format to parse.

https://getsentry.atlassian.net/browse/NATIVE-375

fixes #178 (line numbers capped were u16, we extended that to u32)
fixes #330 (parent_offset capped at u16, the complete concept was removed)
fixes #405 (function size capped at u16, the function size was removed)

### CODE REVIEW

File: symbolic-symcache/src/compat.rs [hunk 1]
```diff
@@ -0,0 +1,288 @@
...
+pub struct Function<'data>(FunctionInner<'data>);
+
+impl<'data> Function<'data> {
+    /// The ID of the function.
+    pub fn id(&self) -> usize {
+        match &self.0 {
+            FunctionInner::Old(function) => function.id(),
+            // TODO: Is there something better we can return here?
+            // I doubt anyone actually cares about this.
+            FunctionInner::New(_) => usize::MAX,
```
Comment (Swatinem) [inline symbolic-symcache/src/compat.rs:143]: I agree, probably noone will care. But I still think we should at least return something unique, which in that case would just be the function index.

File: symbolic-symcache/src/compat.rs [hunk 2]
```diff
@@ -0,0 +1,288 @@
...
+            FunctionInner::Old(function) => function.compilation_dir(),
+            FunctionInner::New(function) => function.comp_dir().unwrap_or_default(),
+        }
+    }
+
+    /// An iterator over all lines in the function.
+    pub fn lines(&self) -> old::Lines<'data> {
+        match &self.0 {
+            FunctionInner::Old(function) => function.lines(),
+            FunctionInner::New(_) => unimplemented!(),
```
Comment (Swatinem) [inline symbolic-symcache/src/compat.rs:205]: instead of a hard panic, lets just define an empty iterator here for now.

File: symbolic-symcache/src/new/lookup.rs [hunk 3]
```diff
@@ -99,18 +96,18 @@ impl<'data> File<'data> {
         self.path_name
     }
 
-    /// Resolves and concatenates the full path based on its individual fragments.
-    pub fn full_path(&self) -> String {
-        let comp_dir = self.comp_dir().unwrap_or_default();
-        let directory = self.directory().unwrap_or_default();
-        let path_name = self.path_name();
+    ///// Resolves and concatenates the full path based on its individual fragments.
```
Comment (Swatinem) [inline symbolic-symcache/src/new/lookup.rs:99]: might as well keep this, maybe mark it with `#[allow(dead_code)]`

File: symbolic-symcache/src/new/raw.rs [hunk 4]
```diff
@@ -10,7 +10,7 @@ const SYMCACHE_MAGIC_BYTES: [u8; 4] = *b"SYMC";
 /// The magic file preamble to identify SymCache files.
 ///
 /// Serialized as ASCII "SYMC" on little-endian (x64) systems.
-pub const SYMCACHE_MAGIC: u32 = u32::from_be_bytes(SYMCACHE_MAGIC_BYTES);
+pub const SYMCACHE_MAGIC: u32 = u32::from_le_bytes(SYMCACHE_MAGIC_BYTES);
```
Comment (Swatinem) [inline symbolic-symcache/src/new/raw.rs:13]: this change here is wrong and would result in a byte flip.
We want this magic constant to be serialized as `"SYMC"` on x64 machines. Maybe we can even assert that in a test:
`buf.starts_with(b"SYMC")`

BTW, there is a `cfg()` attribute that checks for endianness which we should use in that case.

Maybe have @jan-auer double-check this, since we had a couple of discussions regarding endianness previously. The existing old symcache is not endian-aware for that matter. It would fail at the version check in that case.

File: symbolic-symcache/src/new/writer.rs [hunk 5]
```diff
@@ -182,11 +158,8 @@ impl SymCacheConverter {
     pub fn process_symbolic_function(&mut self, function: &Function<'_>) {
         let comp_dir = std::str::from_utf8(function.compilation_dir).ok();
 
-        let entry_pc = if function.inline {
-            u32::MAX
-        } else {
-            function.address as u32
-        };
+        // Is this correct for inlined functions?
+        let entry_pc = function.address as u32;
```
Comment (Swatinem) [inline symbolic-symcache/src/new/writer.rs:162]: maybe add a comment that we are doing this purely for the reason to keep the changes to the snapshot of `functions` minimal. For inlined functions this indeed does not make sense.

But consider this:

We have a function which exists *both* as a freestanding toplevel function, *and* as an inlined function.
IMO, the `function_idx` would point to the toplevel function in that case, similar to how `DW_AT_abstract_origin` works.

Additional metadata which might be interesting for the future would be: file/line where this function is defined. We don’t expose that at the moment, but might in the future. That info would be the same no matter if the function is being inlined or not.

On the other hand, we save generic instanciations separately. So `a<u32>` would create a different function record from `a<u64>`, they have different `entry_pc` (if they are freestanding), but the same declaration file/line.

File: symbolic-symcache/src/preamble.rs [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+}
+
+impl Preamble {
+    pub(crate) fn parse(buf: &[u8]) -> Result<Self, SymCacheError> {
+        let preamble_size = mem::size_of::<Self>();
+
+        if buf.len() < preamble_size {
+            return Err(SymCacheErrorKind::BadFileHeader.into());
+        }
+        // SAFETY: we checked that the buffer is well aligned and large enough to fit a `Preamble`.
```
Comment (Swatinem) [inline symbolic-symcache/src/preamble.rs:25]: maybe not "well aligned". But `#[repr(packed)]` essentially removes all alignment constraints.

**Review by Swatinem — COMMENTED** [review]
Since the `Functions` snapshots use their own `Debug` wrapper, maybe we can collect and sort the functions in there?
That way we minimize snapshot differences.
The other snapshot essentially just differs in indentation (aka more private things in the `Debug` wrapper). Not sure if it might be worth to write a custom `Debug` impl that avoids serializing the `Inner(Old(` internals?

File: symbolic-symcache/src/new/raw.rs (hunk 4 above)
Comment (loewenheim) [reply symbolic-symcache/src/new/raw.rs:13]: I changed this because some tests were failing due to it. Something weird's going on.

Comment (loewenheim) [reply symbolic-symcache/src/new/raw.rs:13]: I added the `buf.starts_with(b"SYMC")` assertion to numerous tests and they all succeed. I think this might have just been wrong before.

File: symbolic-symcache/src/compat.rs [hunk 7]
```diff
@@ -73,6 +73,7 @@ impl<'data> SymCache<'data> {
     }
 
     /// Returns true if line information is included.
+    #[deprecated(since = "0.8.6", note = "this will be removed in a future version")]
```
Comment (Swatinem) [inline symbolic-symcache/src/compat.rs:76]:
```suggestion
    #[deprecated(since = "8.6.0", note = "this will be removed in a future version")]
```

**Review by Swatinem — COMMENTED** [review]
So we have deprecated the `functions()` iterator. Maybe also put such a marker on the structs, `Functions` and `Function`.

Also I think you only need to put these markers on the public functions, and not on the ones that you forward for compatibility reasons.
That way you should not get internal deprecation warnings, and have these internal things flagged as dead code once you remove the public API.

**Review by Swatinem — APPROVED** [review]
