### PR TITLE
fix(symcache): Fixed bug that caused functions to have len 0

### LINKED ISSUE #285: symbolic fails lookup if the lookup address doesn't line up exactly with line record
When symbolic looks up 0x3c105a1 in `xul.pdb/88FD491257B2E0F54C4C44205044422E1`, it fails the lookup, but it should return `Interpret(JSContext*, js::RunState&)`.

The sym file is at: https://symbols.mozilla.org/xul.pdb/88FD491257B2E0F54C4C44205044422E1/xul.sym

Here's the relevant bits in the sym file:

```
MODULE windows x86_64 88FD491257B2E0F54C4C44205044422E1 xul.pdb
INFO CODE_ID 5ED439916EB4000 xul.dll
...
FILE 16693 hg:hg.mozilla.org/mozilla-central:js/src/vm/Interpreter.cpp:e4b11f027efc1f8c2710ae3f52487a8f10a8fb39
...
FUNC 3c01d20 1f6e8 0 Interpret(JSContext*, js::RunState&)
...
3c104e1 c 3021 16693
3c104ed 10 3070 16693
3c104fd e2 3071 16693
3c105df 10 3076 16693
3c105ef 9 3077 16693
3c105f8 c 3078 16693
3c10604 20 3079 16693
```

Breakpad stackwalker returns `Interpret(JSContext*, js::RunState&)` at `js/src/vm/Interpreter.cpp:3071`.

### PR DESCRIPTION
**Pull request by loewenheim**
This fixes #285. The problem wast that in the line https://github.com/getsentry/symbolic/blob/c964bbad31bc7f789a9ead918385babf3aa6d7e2/symbolic-symcache/src/writer.rs#L516
`len` could be 0 if `end_address - start_address` was a multiple of 2^16.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Classic

File: symbolic-symcache/src/writer.rs [hunk 1]
```diff
@@ -513,8 +513,12 @@ where
...
-            debug_assert_ne!(len, 0, "Function length must be positive");
+            let len = std::cmp::min(end_address - start_address, 0xffff) as u16;
+            debug_assert_ne!(
+                len, 0,
+                "While adding function {}: length must be positive",
+                function.name
+            );
 
             let len = match NonZeroU16::new(len) {
                 Some(len) => len,
```
Comment (jan-auer) [inline symbolic-symcache/src/writer.rs:524]: Let's also `break` below, to avoid endless loops. Sorry about that, this was my mistake in the previous review suggestion.

**Review by jan-auer — APPROVED** [review]
